### ISSUE TITLE
Feature: menu/other UI from header avatar with username

### ISSUE THREAD

**Issue by tigpt** [open-sauced/open-sauced#1031]
On top bar, when hovering over the avatar it should show the username as text visible to see what username we have logged in.

**Comment by filiptronicek** [comment]
Awesome idea @tigpt, are you imagining just a simple popover like the native [HTML title](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/title) or a fancier one?

![image](https://user-images.githubusercontent.com/29888641/120861021-eef11a80-c586-11eb-9440-695881326369.png)

**Comment by tigpt** [comment]
Actually it was Brian idea on twitch and I just logged it here so we don't forget :)

That looks nice for first implementation and then we can add some css. Are we using any css framework on this project that we can reuse the tool tips?

**Comment by filiptronicek** [comment]
@tigpt I don't think we are using any framework for the styles, every design is ours.

**Comment by bdougie** [comment]
Looks like we get names when hovering over contributors in the repository dahsboard.

![Screen Shot 2021-06-11 at 2 25 36 PM](https://user-images.githubusercontent.com/5713670/121750282-f18ccc00-cac0-11eb-81f5-babd370c6d5d.png)

**Comment by 0-vortex** [comment]
On the top right bar, that's where a user menu style popunder is generally used - currently, the real problem is no hover over the button indicating clicking it will redirect the user to your GitHub profile page, making the action unpredictable unless memoized.

While this is not ideal UX, IMO we could use a clickable popunder in order to:
- disable the ability to teleport to GitHub without requesting it
- have additional information about open sauced (version, app id status, etc) 
- enable some feedback mechanism
- condense the logout button behind a 2nd click, in order not to log out by accident
- ^ + remove low priority log out option from the first web site menu (a11y)

**Comment by filiptronicek** [comment]
I love the idea, @0-vortex!

**Comment by mtfoley** [comment]
updated title to reflect the suggested feature as it is, reset as good first issue.

**Comment by RizelBobb** [comment]
.take

**Comment by RizelBobb** [comment]
.take
