### ISSUE TITLE
Feature: Create redesign for home page/landing page

### ISSUE THREAD

**Issue by blackgirlbytes** [open-sauced/open-sauced#1304]
### Type of feature

Feature

### Current behavior

Currently when you go to opensauced.pizza, you get these views for dark mode and light mode:

<img width="1792" alt="Screen Shot 2021-11-14 at 3 07 24 PM 1" src="https://user-images.githubusercontent.com/22990146/141696806-cb4af449-b20d-403a-8179-85cd68fdc612.png">
<img width="1792" alt="Screen Shot 2021-11-14 at 3 07 30 PM" src="https://user-images.githubusercontent.com/22990146/141696813-52e65058-6a35-4734-a3b4-6b127d849f1d.png">

### Desired solution

We want to revamp the site slowly to be be more modernized. They made this project a few years ago, but there are more modern design practices that people are using in 2021.

The plan is for @LuluNwenyi to work on the designs for this and @blackgirlbytes to write the code for this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 0-vortex** [comment]
Sounds great, feel free to take the issue :D

Excited for new stuff 🍕

**Comment by blackgirlbytes** [comment]
Yay, I'm glad yall are excited.

@lulunweny actually asked me "Any idea what theme you think bdougie or the other maintainers have in mind?" I told them mayyyybe more modern like tailwindcss.com's landing page but if yall have more ideas and better answers, please let us know because I'm not too sure!

**Comment by mtfoley** [comment]
@bdougie has prob talked about it a handful of times on his stream but I doubt those segments have been clipped before - one of us can try to ping him during the stream on Wednesday to see if there’s a look and feel that he’s partial to!

FWIW I seem to remember that the existing design had its roots in Netlify’s design system at the time (~2016) - I’m not sure how it’s evolved over time.

**Comment by blackgirlbytes** [comment]
Okay, I'll try to ask him some more at work too! I completely forgot I could just DM him hahaha 🤦‍♀️

**Comment by mtfoley** [comment]
I know he’s been messing with Astro and Supabase lately so there might be some recency effects there 😜

**Comment by 0-vortex** [comment]
> Yay, I'm glad yall are excited.
> 
> @lulunweny actually asked me "Any idea what theme you think bdougie or the other maintainers have in mind?" I told them mayyyybe more modern like tailwindcss.com's landing page but if yall have more ideas and better answers, please let us know because I'm not too sure!

@blackgirlbytes 

Would argue that tailwind is both old design and could bias our design process towards a tailwind implementation but that is not why I want to dismiss it - we should let the creative process flow towards accessibility and inclusion, just like the process of ordering a pizza: you might order in a few times from fancy websites and easy to use platforms but you will rate the quality of the pizza based on taste, how good it is for your health, packaging, etc.

In my humble opinion, we could start a discussion around 2 specific topics, visual impact and accessibility, not for the process of plagiarizing the work of other people but specifically to identify amazing components, potentially augment the creative process with some amazing ideas while extending the reach of their creators.

> @bdougie has prob talked about it a handful of times on his stream but I doubt those segments have been clipped before - one of us can try to ping him during the stream on Wednesday to see if there’s a look and feel that he’s partial to!
> 
> FWIW I seem to remember that the existing design had its roots in Netlify’s design system at the time (~2016) - I’m not sure how it’s evolved over time.

@mtfoley 

Hate to be a "hard no" megaphone but we should not use any existing design system **unless** it is multi-platform compatible (thinking of at least React primitives here or loosely coupled from any CSS-in-JS technique). In that sense, we could start another discussion around existing tooling for theming and design systems but a better first step would be to set the exact scope of how we want to use a more reliable version of [opensauced.pizza](https://opensauced.pizza).

I think the most inclusive solution here is to keep using React ecosystem (sorry Vue and Angular), have a baseline that can translate to multiple platforms without relying solely upon PWA/SW which essentially means React/React Native cross and final key point, be compatible with our maintainer and contributor experience so far, so [CRA](https://github.com/facebook/create-react-app), [Next](https://nextjs.org) and [Expo](https://expo.dev)

Something I would like to tease here is content from the [Next conf](https://nextjs.org/conf), the underdog: [dripsy](https://www.dripsy.xyz). As a community, we could spend several months experimenting with the ecosystem maybe even have some potential adversarial solutions we can all learn from. Since our users could be both technical and non-technical people, it is difficult for any one of us to envision the final result without working together and in contrast to our knowledge!

At the moment, it is quite difficult to get into contributing to the project visually without some basic frontend development experience, and we could totally change that, make every part of the process open and observable 🍕

**Comment by blackgirlbytes** [comment]
Yeah I like the idea of putting accessibility first here.

**Comment by mtfoley** [comment]
Yeah with respect to the two apps I mentioned I really just meant look and feel, not necessarily the design system itself. 

+1 for a11y

**Comment by blackgirlbytes** [comment]
yeah me too!

**Comment by bdougie** [comment]
Hey, @blackgirlbytes thanks for opening this. In short, the current design is styled-components with the majority of the design decisions originally from me or crowdsourced on stream. I am open to all ideas and happy to sit down with anyone willing to chat about approaching this. 

> "Any idea what theme you think bdougie or the other maintainers have in mind?" 

Modern and approachable is what I have in mind. Taking cues from other projects is ideal. I linked the brand standards below. This was created by a friend a few years back.

[open_sauced_brand_standards_manual.pdf](https://github.com/open-sauced/open-sauced/files/7540567/open_sauced_brand_standards_manual.pdf)

**Comment by 0-vortex** [comment]
> Hey, @blackgirlbytes thanks for opening this. In short, the current design is styled-components with the majority of the design decisions originally from me or crowdsourced on stream. I am open to all ideas and happy to sit down with anyone willing to chat about approaching this.
> 
> > "Any idea what theme you think bdougie or the other maintainers have in mind?"
> 
> Modern and approachable is what I have in mind. Taking cues from other projects is ideal. I linked the brand standards below. This was created by a friend a few years back.
> 
> [open_sauced_brand_standards_manual.pdf](https://github.com/open-sauced/open-sauced/files/7540567/open_sauced_brand_standards_manual.pdf)

This is epic stuff, not sure how many people are aware of this. How do you feel about creating a "Design" category in our docs?

**Comment by LuluNwenyi** [comment]
> Hey, @blackgirlbytes thanks for opening this. In short, the current design is styled-components with the majority of the design decisions originally from me or crowdsourced on stream. I am open to all ideas and happy to sit down with anyone willing to chat about approaching this.
> 
> > "Any idea what theme you think bdougie or the other maintainers have in mind?"
> 
> Modern and approachable is what I have in mind. Taking cues from other projects is ideal. I linked the brand standards below. This was created by a friend a few years back.
> 
> [open_sauced_brand_standards_manual.pdf](https://github.com/open-sauced/open-sauced/files/7540567/open_sauced_brand_standards_manual.pdf)

Hi @bdougie we could chat about it.. It would give @blackgirlbytes and myself a clearer view of what the team would prefer to go with.

**Comment by blackgirlbytes** [comment]
> > Hey, @blackgirlbytes thanks for opening this. In short, the current design is styled-components with the majority of the design decisions originally from me or crowdsourced on stream. I am open to all ideas and happy to sit down with anyone willing to chat about approaching this.
> > > "Any idea what theme you think bdougie or the other maintainers have in mind?"
> > 
> > 
> > Modern and approachable is what I have in mind. Taking cues from other projects is ideal. I linked the brand standards below. This was created by a friend a few years back.
> > [open_sauced_brand_standards_manual.pdf](https://github.com/open-sauced/open-sauced/files/7540567/open_sauced_brand_standards_manual.pdf)
> 
> This is epic stuff, not sure how many people are aware of this. How do you feel about creating a "Design" category in our docs?

I think that's a good idea, especially after we finalize the new designs for this.
