### ISSUE TITLE
Create Onboarding step 2 image/tooltip

### ISSUE THREAD

**Issue by bdougie** [open-sauced/open-sauced#1433]

**Comment by chadstewart** [comment]
To resolve issue #862, we have implemented a new onboarding flow that moves away from having two separate screens that gives you instructions on how to proceed to one screen with a list of steps so that users know how many steps to get access to open-sauced. In that conversion, the details to the step 2 process was lost as the image and verbiage of the second screen was removed. This needs to be replaced with something that will describe to users how to complete step 2 but also fits into the new design.

A suggested way of solving this issue would be to add a tooltip to the second card that shows the image and instructions on how to complete step 2 of the process.
