### ISSUE TITLE
Bug: Forking doesn't work

### ISSUE THREAD

**Issue by tplive** [open-sauced/open-sauced#1461]
### Describe the bug
[Edit: I edited the expected result of the bug as well as the steps to reproduce]

When I click the Fork button, there is no fork created. When I go to the repo outside Open Sauced, and fork it, there is a dialog that has no default choice, regarding the owner of the fork. As I represent several organisations, and none is chosen by default, I suspect this is where the forking process stops? 🤷
Can anyone with a GH user that belongs to several orgs confirm or deny? 😄 

![image](https://user-images.githubusercontent.com/1882635/188436501-c8e91edc-dd72-4c30-a150-42f47a58d72a.png)

### Steps to reproduce

1. Go to your Open Sauced dashboard
2. Add a repo to sync
3. Open the repo
4. Hit Fork. It changes to View Fork
5. Click View Fork
6. You land at a Github 404 page pointing to where the fork should be, but there is no fork.

### Affected services

opensauced.pizza

### Platforms

Desktop

### Browsers

Firefox

### Environment

Production

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by Deadreyo** [comment]
I will `.take` this

**Comment by Deadreyo** [comment]
So after some inspection, what I found is:

![image](https://user-images.githubusercontent.com/52013393/194431825-78936533-8a81-4f24-9092-82d5151e2737.png)

1- The `forkRepository` function uses a wrong api function. It uses `persistedForkFetch`, which is actually responsible for retreiving the number of forks made from that repo by that user, and it does NOT create a new fork.

2- Since it points to an api call that retreives data, this will never fail, so there will never be an error, and so the `setIsForked(true);` will be run, even though nothing was created.
