### ISSUE TITLE
Reloading the page shows login page for a small time

### ISSUE THREAD

**Issue by yg** [open-sauced/open-sauced#525]
Reloading the page shows login page for a small-time

https://www.loom.com/share/5fab6c11a7a648e599a1d42b73411d91

/cc @bdougie

**Comment by bdougie** [comment]
The storing of the auth token, after you have logged in, needs to be set in a database or local storage. I think that is what is happening here--the app does not remember if you have logged in and boots you back to the login and until it figures it out. 

We solved on the githubhackathon.com (that site is built similar to opensauced) by setting the token in a cookie. The code is not open-sourced, but below is snippet.

[auth.js](https://gist.github.com/bdougie/5aa1d6d4b027db3afd92111369768f17)

**Comment by bdougie** [comment]
I discovered a fix and will need to clean it up a bit but in short this: https://github.com/open-sauced/open-sauced/blob/master/src/containers/App.js#L16, instead of the user object that needs to be a boolean. 

I have some code to set an `isLoggedIn` similar to the `isAdmin`. Instead of local storage though, I am setting a cookie. Once working, I will set this up so a notify function can perform this in the background too. 

Examples:

```
const [isLoggedIn, setLogin] = useState(getCookieValue("isLoggedIn") === "true");

useEffect(() => {
    const auth = Config.auth;
    auth.isLoggedIn("github").then(isLoggedIn => {

 if (isLoggedIn) {
        setCookie("isLoggedIn", "true")
...
}
...

 <App
   user={user}
   isLoggedIn={isLoggedIn}
   isAdmin={isAdmin}
/>
```
This will be helpful in the event we want to set up roles-based redirects for user types. It is only a little more code and opportunity to leverage Netlify more. Considering there are plans to have maintainer only features.

**Comment by yg** [comment]
Nice Idea @bdougie
