### ISSUE TITLE
AdminStats bar for maintainers

### ISSUE THREAD

**Issue by yg** [open-sauced/open-sauced#573]
### Describe the solution you'd like

Performance bar for that is visible only for open sauced maintainers

- Current working branch
- Version of React
- Total Render Time
- Number of API Calls
- Cache
- etc

### GitHub - Screenshot from this [Video](https://www.youtube.com/watch?v=VDGP07RJcWA)

![PB1](https://user-images.githubusercontent.com/61746440/77838286-601d8c80-7190-11ea-97e7-51141c0f1ecc.png)
![PB2](https://user-images.githubusercontent.com/61746440/77838288-614eb980-7190-11ea-9847-6071683e9204.png)

### GitLab

![GLPB](https://user-images.githubusercontent.com/61746440/77838291-6449aa00-7190-11ea-99d2-00df04c2fb91.png)

**Comment by yg** [comment]
@bdougie I have some questions in designing context/performance bar?

How can we call it context/performance bar?
How can we fetch only the maintainers from open-sauced GitHub org?
Is Onegraph provide API for Netlify?

**Comment by bdougie** [comment]
I think for now we can we can this idea as a AdminStats bar.

Because we now use an org we can create a check for logged in user ids and check if the logged in user is a member the team_id.

For example we are both in the maintainer team and can hide this and other features for admins only.

Those are my initial thoughts.

I think first steps is creating or finding a library to toggle react components if the user is an admin. Once that is established we could proceed with creating the bar.
