### ISSUE TITLE
Don't allow the creation of goal if the repo is deleted or not existed in GitHub

### ISSUE THREAD

**Issue by yg** [open-sauced/open-sauced#600]
Don't allow the creation of goal if the repo is deleted or not existed in GitHub

### To Reproduce

1. Try adding the repo which does not exist or deleted from GitHub
2. We can see the Repo page loads infinitely

### Expected behavior

Show an error that repo does not exist

**Comment by filiptronicek** [comment]
It could also check whether the repo is archived or not -> you cannot contribute to read-only repos.
![image of the GitHub REST API](https://user-images.githubusercontent.com/29888641/83759731-4c9d0f00-a674-11ea-9e0a-fab4afd5667a.png)

**Comment by bdougie** [comment]
good catch @filiptronicek. Definitely something else we should consider when fixing this.

**Comment by bdougie** [comment]
This is related to https://github.com/open-sauced/open-sauced/issues/643

I don't think we should prevent a goal from being opened, since cloning the repo is an option. I think we can instead update the open-sauced-goals issue to get labeled as `archived`. We can use the label note that repo is archived in case the user wants to make a goal or revive the projects themselves. 

I started to outline that here https://github.com/open-sauced/goals-template/issues/9

**Comment by yg** [comment]
@bdougie This is fixed in #728
