### ISSUE TITLE
Blank screen after login

### ISSUE THREAD

**Issue by bdougie** [open-sauced/open-sauced#617]
### To Reproduce

1. logout while on the dashboard goals.
2. login again and see blank
### Screenshots

![ezgif com-video-to-gif (2)](https://user-images.githubusercontent.com/5713670/83914296-d6f17b80-a725-11ea-8dec-23a560173608.gif)

### Desktop

- OS: macOS
- Browser: Chrome
- Version: 86

### Additional context

This is happening when you are ina goal and logout and then login.

**Comment by bdougie** [comment]
This could be solved by adding better routing. At the moment we don't respect the /repos routes. 

I outline this in #639, but we would following the pattern. 

## Scenario
When a user navigates to an opensauced.pizza/repos/owner/repo they should be presented with a dashboard associated with that goals.

If there is no goal already created, once should be created for them, as long as they are logged in. 

## Solution

1. Add a dynamic route to [App.js](https://github.com/open-sauced/open-sauced/blob/master/src/containers/App.js#L65). i.e.` path="/repos/:owner/:name`
2. Add logic to create the repo if there is a 404 returned, repoStatusCode solution mentioned in https://github.com/open-sauced/open-sauced/issues/654#issuecomment-644807898

**Comment by jnielson94** [comment]
.take

**Comment by bdougie** [comment]
Awesome, let us know if you have any questions. My solution may be incorrect, but it may assist in debugging the cause.

**Comment by jnielson94** [comment]
I did some digging since #726 didn't fix the actual issue reported here (though it did fix my issue of the app giving a blank screen the first time you login). 

I've done a little bit of digging and the blank screen seems to be caused by this line throwing an error: https://github.com/open-sauced/open-sauced/blob/145eb1d1b8cd9b8bc0c51b430c2d4c653e3888cc/src/lib/reducers.js#L7

Since `state.repository` doesn't exist, and when you logged out the cached value for state ended up with an error related to no github auth existing, and `state.data.github` is null. Ideally the fix seems like it would involve avoiding the error in the cache when you log back in so that a spinner can show, but I haven't figured out how to clear the cache.
