### ISSUE TITLE
Bug: Buggy repo listing

### ISSUE THREAD

**Issue by filiptronicek** [open-sauced/open-sauced#685]
### Describe the bug
When a repo name is very long, it breaks the whole UI (very easy to reproduce on mobile)

### To Reproduce

1. Use a device or change the window to a small width (mobile is best)
1. Add a repo with a long name
### Expected behavior
The text doesn't overflow.

### Screenshots
![screenshot with long name](https://user-images.githubusercontent.com/29888641/84668819-5bad7800-af24-11ea-88bc-4425c36b6a9f.png)

### Desktop

- OS: Win 10
- Browser: Firefox Developer Edition
- Version: Latest

### Smartphone

- Device: iPhone Xs
- OS: iOS 13.5.1
- Browser: Safari
- Version: latest

### Additional context
Setting a max length wouldn't be the best solution -> I would limit the display size - not the stored size

**Comment by bdougie** [comment]
This can be easily fixed by truncating URLs to 100 characters.

Steps to fix: 

1. Create truncate.js similar to [humanizeNumber.js](https://github.com/open-sauced/open-sauced/blob/master/src/lib/humanizeNumber.js).
2. Wrap the following places with the truncate function

https://github.com/open-sauced/open-sauced/blob/master/src/components/RepoListItem.js#L15
   
https://github.com/open-sauced/open-sauced/blob/d28b6c945da0733480c88045b4249d02afadd29f/src/components/Repository.js#L69

3. Please write a test.

Solution
```js
  <h1>{truncate(nameWithOwner)}</h1>
```

**Comment by yg** [comment]
@bdougie I will work on it!
