### ISSUE TITLE
Bug: 404 not found... literally

### ISSUE THREAD

**Issue by filiptronicek** [open-sauced/open-sauced#688]
### Describe the bug
When 

### To Reproduce
1. Go to opensauced.pizza
1. Append /repos/`your username`/`some random string` to the URL

### Expected behavior
The default 404 page is shown

### Screenshots
![image](https://user-images.githubusercontent.com/29888641/84686834-f9ad3c80-af3c-11ea-9124-e5d550a36773.png)

### Additional context
Probably a problem with the routing ->seems that the router gets confused when a repo is not present your goals.

**Comment by bdougie** [comment]
This is a known thing. It would be nice to handle the case like so:

Navigate to any /repos/owner/name URL and do the following.
1. open the repo data based on the URL
2. if the issue is not open in the goals repo, then open it and proceed with showing the data
3. If the repo is misspelled or does not exist, present the error message stating on the screen. related to #654

**Comment by bdougie** [comment]
Solution would be adding a route that expects params. I actually this enforced a few years back, but it was removed in a react-router migration I did. 

https://github.com/open-sauced/open-sauced/issues/688#issuecomment-644372220

```js
<Route path="/repos/:owner/:name" component={guard(Dashboard)} />
```

**Comment by filiptronicek** [comment]
.take
