### ISSUE TITLE
Feature: Add ability to have the "database" be a private repo

### ISSUE THREAD

**Issue by JosephLing** [open-sauced/open-sauced#772]
### Is your feature request related to a problem? Please describe.
It's awesome that you get to write notes for each repository however sometimes it would be handy to have those notes be private. Specailly if the database model is used to store any additional information in the future.

### Describe the solution you'd like

Add the option to have the database run from a private repository instead of a public one. That way people can decide what they want to do with their data. 

From briefly looking through the code it should be possible to add in a field to set the visibilty to "private" when cloning. 
[clone api docs](https://docs.github.com/en/graphql/reference/input-objects#clonetemplaterepositoryinput). 

In terms of for issues I think it should be as app already requests the correct permissions for private repos.

The difficulty then lies in having two modes public and private. And how that wants to be handled maybe.....
- just private (all new databases are private and in another PR add in migration for exisitng databases if people want to migrate)
- public and private (public for public repos and private for private repos maybe if people want)
- public or private (opt in on per repo basis)

### Describe alternatives you've considered

Add a label to the notes button/area to highlight that all notes are public.

**Comment by bdougie** [comment]
## Background on Public/Private
This app actually made all notes as private by default prior to #533. 

I see the value for private note-taking as a user, but at the moment there is low open-sauced project benefit making the DB private, mainly because the notes are unstructured and can be taken anywhere. In the future, I would like to focus on structuring the note content and guiding the user to take notes on repos using prompts, with guide notetaking it will be easier to take free form notes to a private forum.

Two major migrations are happening right now, which makes adding this Private option challenging. Not to mention it will make the migrations challenging as well:

### Migrations
1. Migration to leverage the Repo metadata and keeping that in sync using GitHub Actions: https://github.com/open-sauced/open-sauced/issues/667
2. Migration from an OAuth App to a GitHub App (This will allow us to add access to private repo info for only open-sauced-goals): https://github.com/open-sauced/open-sauced/issues/689

The app indeed assumes Public repos in the interaction with GitHub API today, but I am happy to consider this Private option more after the 1.0.0 release. 

## Benefits for Public repos
1. Discoverability for this project is a motivator, and though I have not to view user data directly in their repos it is nice for maintainers to identify that their project and issues are being tracked by open sauced. (Today the app is 71 users, this is based on counting public repos, we would not be able to see or count private repos). 
2. Having access to the only public allows developers that use GitHub for work and private projects the confidence that the project is not viewing.
3. This project is meant for open source contributions and having the notes in the open is beneficial for future contributors/maintainers. 

## Potential solutions for private notes
1. Instead of free notes in open-sauced, we can provide links to another service where notes can be taken privately. Open to suggestions that would support the "owner/repo" structured in the URL to make it linkable from the open-sauced dashboard.
2. Provide structure to note-taking and only request information users are willing to publicly (I would love to conduct user testing to find out what type of notes users are writing).

## Structured notetaking for easier private migration.
My rough thoughts on structured note-taking are based on the way I have taken notes in the past: https://github.com/bdougie/open-sauced-goals/issues/17. 

Listing here, so I can eventually open an issue. 

- User can select issues they are interested in and store them in the notes section.
- User can identify steps to take onboard and contribute to a project.
- User can identify key stakeholders for ask questions. (check for [CODEOWNERS](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners#codeowners-syntax) file)
- User can identify the location the synchronous conversation is happening (probably discord).

**Comment by bdougie** [comment]
For now, we are going to focus on some other things. Might consider a new path towards note taking in the future. Linking issues can be noisy.
