### ISSUE TITLE
Bug: View Fork button not being displayed when selecting a repository that has already been forked.

### ISSUE THREAD

**Issue by jasonericdavis** [open-sauced/open-sauced#883]
### Describe the bug

When selecting a repository that has already been forked by the user the "View Fork" button should be shown. Instead the "Fork" button is shown. 

### To Reproduce

1. Go to opensauced.pizza
2. Click on a repository that has already been forked.
3. The "Fork" button is displayed instead of the "View Fork" button.

### Expected behavior

When selecting a repository that has already been forked the "View Fork" button should be displayed

### Screenshots

v 0.18.1 (Showing it not working)
![Screen Shot 1](https://user-images.githubusercontent.com/14043845/98447515-562f1500-20f3-11eb-918a-5c6a30e8273b.png)

v 0.17.3 (Showing it working in a previous version)
![Screen Shot 2](https://user-images.githubusercontent.com/14043845/98447532-7b238800-20f3-11eb-8a89-40b2fdaa9f70.png)

### Additional context

If you look in the screenshot you can see the bug was created between versions 0.17.3 and 0.18.1. I was also able to verify that the FetchUserForkCount persisted query is returning totalCount:0 which makes me believe this issue may be related to changes in #699. 

When I run the query in one graph with the values {repoName: "open-sauced", repoOwner: "open-sauced"} the query returns a totalCount: 1 which is expected but if I use variables for a repository that I created the totalCount is 0. In open sauced if I select that same repository the "View Fork" button is displayed.

**Comment by filiptronicek** [comment]
It looks like another output gets written to the browser console, that being
`TypeError: can't access property "viewer", n.data.gitHub is null`

![browser console screenshot](https://user-images.githubusercontent.com/29888641/100114620-e7331980-2e71-11eb-9252-27b0f2c47834.png)

It looks like the transfer to limited Oauth data disabled access to the `n.data.gitHub variable`...

I will try to look more into this, I wonder if @bdougie has any ideas?

**Comment by jasonericdavis** [comment]
I also think that it is worth looking into the context in which OneGraph is executing the query. It seems as though the OneGraph query is running as someone other than the person that is logged in.  When I log into my own Onegraph account in a separate browser and run the query using open-sauced as the repository (which I am not an owner) I get back the expected response. If I run the query using a repository that I own then I get the result that I am seeing in open-sauced.

**Comment by mtfoley** [comment]
I had been noticing this issue too. Interestingly enough, I was looking at a repo I'd already forked and had also added as a goal in opensauced.pizza, and clicked the fork button in GitHub, which took me to my existing fork. Since then, the View Fork button has been working for me. Call me crazy, but I feel like there's some kind of cache that I updated by doing that.

**Comment by 0-vortex** [comment]
Looking at the [onegraph docs](https://www.onegraph.com/docs/logging_users_in_and_out.html) about auth and then the code, just a wild thought but could this be related to the `isLoggedin` variable in the dashboard  `useEffect` at https://github.com/open-sauced/open-sauced/blob/0480f67efe88aff380055734c16cf5321ccf5bd2/src/index.js#L24-L57 ?

Some context from the most recent stream:

https://clips.twitch.tv/LaconicCuteSardineDxAbomb-0o6cyQ3KaX4y3UPA

https://clips.twitch.tv/CuteDepressedPuffinWOOP-giOUmm9N_itsAVEo

**Comment by mtfoley** [comment]
Disclaimer: I may have missed the original point here, but anywho...

I haven't yet taken time to watch the twitch streams that @0-vortex sent. However as I look over the code, the behavior that @jasonericdavis is describing makes some sense. I believe the data that populates the "View Fork" button or other version of the UI comes from the GraphQL query "FetchUserFork" that @jasonericdavis pointed out in [here](https://github.com/open-sauced/open-sauced/blob/main/src/lib/apiGraphQL.js) and [here](https://github.com/open-sauced/open-sauced/blob/main/src/components/Repository.js). That query is like this:
```GraphQL
query FetchUserForkCount(
    $repoName: String!
    $repoOwner: String!
  ) {
    gitHub {
      repository(name: $repoName, owner: $repoOwner) {
        forks(affiliations: OWNER) {
          totalCount
        }
      }
    }
  }
```
Reading the [GitHub GraphQL docs](https://docs.github.com/en/graphql/reference/objects#repository), it looks like it's counting the number for **forks** that the logged in user is the OWNER of. I suppose we could look at what happens if this query is modified to include the [COLLABORATOR and/or ORGANIZATION MEMBER enums](https://docs.github.com/en/graphql/reference/enums#repositoryaffiliation), to see what that changes. However, if you're making an open-sauced goal for a repo (rather than a fork for a repo) that you own or are part of the project team, maybe there should be an alternate UX to the Fork/View Fork buttons? Perhaps a question for @bdougie.
