### ISSUE TITLE
Bug: Potential Bugs and Anti-Patterns in the Codebase

### ISSUE THREAD

**Issue by HarshCasper** [open-sauced/open-sauced#894]
## Description 

I ran DeepSource Static Code Analysis upon the Project, the results for which are available [here](https://deepsource.io/gh/HarshCasper/open-sauced/). 

The Static Code Analysis Tool found potential bugs and anti-patterns in the Code, that can be detrimental at a later point of time with respect to the Project. DeepSource helps you to automatically find and fix issues in your code during code reviews. This tool looks for anti-patterns, bug risks, performance problems, and raises issues. 

Some of the notable issues are: 

- Unused Variables and Undeclared Variables [here](https://deepsource.io/gh/HarshCasper/open-sauced/issue/JS-0128/) and [here](https://deepsource.io/gh/HarshCasper/open-sauced/issue/JS-0125/).
- No Return Statements in Callbacks [here](https://deepsource.io/gh/HarshCasper/open-sauced/issue/JS-0042/)
- Restricted Global Variables being [used](https://deepsource.io/gh/HarshCasper/open-sauced/issue/JS-0122/)
- Lack of Alternative Text [here](https://deepsource.io/gh/HarshCasper/open-sauced/issue/JS-0737/)
- Improper Use of Anchors [here](https://deepsource.io/gh/HarshCasper/open-sauced/issue/JS-0739/)

There are plenty of other issues in relation to Bug Discovery and Anti-Patterns which you would be interested to take a look at.

**Comment by mtfoley** [comment]
.take

**Comment by mtfoley** [comment]
I have some work underway on this.  I tried to run DeepSource in the same way that @HarshCasper did on my own fork, but it seems like some of the environment settings in DeepSource aren't available in the same way, so the issues it lists are a little overwhelming at the moment. Since it's still live, I'm going to focus on some of the ones in the analysis output that @HarshCasper already linked to:
- no return statements in callbacks
- lack of alternative text
- improper use of anchors

As for the issue of unused variables and [undeclared variables](https://deepsource.io/gh/HarshCasper/open-sauced/issue/JS-0128/occurrences), they appear to fall into one of two categories:
1) imported but unused UI components.
2) variable assignments in test suites that don't get used in the current codebase - it seems like the tests might have made use variables of these at one time, but don't currently.

**Comment by mtfoley** [comment]
I should be finished with PR #941 now.
