### ISSUE TITLE
Feature: add clickable link to the goals repo on the first-time setup

### ISSUE THREAD

**Issue by 0-vortex** [open-sauced/open-sauced#948]
### Is your feature request related to a problem? Please describe.

After installing the Open Sauced GitHub application and creating the "open-sauced-goals" repository a link to it could be clickable before granting rights to the app.

Additional context can help what is happening after clicking the install button.

### Describe the solution you'd like

Add an anchor to open the GitHub repository in a new tab.

Add some additional description instead or before redirecting to the goals repository.

### Additional context

https://clips.twitch.tv/TenaciousKitschyDonkeyOSkomodo-SaSLo_p5485mkNTm

https://clips.twitch.tv/HealthyHealthyNewtPunchTrees-AivvMBrYgJPH3U7W

**Comment by mtfoley** [comment]
.take

**Comment by mtfoley** [comment]
I think I can do a PR that half-solves what's in the clips that @0-vortex linked up.  The redirect is probably something @bdougie would need to do, if anyone.  I don't know exactly how the open-sauced GitHub app is setup, but it looks like it's been configured through OneGraph because below the install button it says the user will be redirected to `http://serve.onegraph.com/oauth/github/receive` which I'm assuming is the callback URL.  It seems to me there's a way of passing state (like `user.login`) along [thru the OAuth flow](https://docs.github.com/en/developers/apps/building-github-apps/creating-a-github-app), but I don't know if OneGraph could be configured to change the callback URL based on that state.

**Comment by mtfoley** [comment]
I unassigned myself since the remainder of this issue (the redirect) would deal with configuration of the open-sauced GitHub app (which would be @bdougie).

**Comment by mtfoley** [comment]
@bdougie I changed a couple of labels, but tbh I don't know what label to apply when it's really just you that can wrap it up - the remainder deals with configuration of the open-sauced GitHub app for callback URLs, etc.

**Comment by bdougie** [comment]
This can actually be done with the GitHub App. Blocked by https://github.com/octokit/app.js/issues/269. Perhaps I can take a crack at contributing to that.

**Comment by 0-vortex** [comment]
Moving away from taking notes and into insights, the new onboarding process would overhaul this and just need down-streaming 🍕
