### ISSUE TITLE
Feature: keep StoryBook updated

### ISSUE THREAD

**Issue by 0-vortex** [open-sauced/open-sauced#952]
### Is your feature request related to a problem? Please describe.

StoryBook has not been updated properly and some stories diverged from existing design implementations.

Could be a good first issue for people looking to learn React tooling and testing.

### Describe the solution you'd like

Remove unused stories and update some of the existing ones to minimal examples.

### Describe alternatives you've considered

Move all the StoryBook stuff to a separate integration repository; skip component testing to straight end to end.

### Additional context

https://clips.twitch.tv/HelpfulBombasticSnailOpieOP-cfVt43dNEbnJCZyk

**Comment by theshakeabhi** [comment]
Hi, I would like to take this issue and work on it as I am new to open source. 
Before '.take' I thought I would ask here if I can take up this issue and work on it.
Can we discuss what all are the unused stories and what all to be updated?

**Comment by 0-vortex** [comment]
@theshakeabhi didn't mean to ignore, what you are asking is the task of this issue - storybook is being passively maintained, the effort of planning or triaging what could be done there exceeds the planned solution scope.

**Comment by theshakeabhi** [comment]
Hi @0-vortex , I saw a 'first good bug' label and I jumped on this issue, as I read your comment I understood that I need to get bit more used to the environment of the project so that I could work on this issue.
I am unassigning myself from this issue for now, so that if there is another person who wants to take this bug up can do that.
Thank you for taking your time and letting me know.

**Comment by chadstewart** [comment]
Hello everyone.

So I pulled the repo down and was looking through the code and storybook (I'm pretty new to it and design systems) and I wanted to ask. Would everything from the components folder of the app need to be added to storybook and how would you make decisions on what variations of UI elements to add? For instance, when would you add different types of buttons or container elements?

**Comment by bdougie** [comment]
TBH, just looking for forward progress here. My expectation would be to have the Cards and Buttons represented in all their forms. They are the most used in the app and will need references. 

## The Goal
Today there are 21 components in the components folder, those 21 should at minimum get representation in the storybook. Each minute detail or primitive could be represented as well, but I would not make that a priority. 

Let us know if you have any other questions. Here or in the Discord works.

**Comment by chadstewart** [comment]
So while working on the storybook issue, I realize that was is in production right now and what is in the main branch may not be the same code. I noticed because the production code has the dark mode feature while the code in the repo does not. Just wanted to bring attention to this in case it was some form of oversight.

**Comment by mtfoley** [comment]
@chadstewart for what it’s worth it does look like your fork is up to date with main, since this file was introduced for dark mode: [ThemeContext](https://github.com/chadstewart/open-sauced/blob/main/src/ThemeContext.js). Two follow up questions I would have: 1) does it make a difference if you clear the cache in the browser dealing with your local testing? I’ve seen this make a difference before. 2) I definitely did not update any of the storybook environment for dark mode, so could that be the difference?

**Comment by chadstewart** [comment]
So I just re-ran the project again and the theme buttons showed up. Spent a while scouring through the project looking for references to the buttons because I couldn't find them anywhere in here. I dunno, maybe I'm just crazy or something. Either way, I found what I needed. Thanks much and sorry about that.

**Comment by bdougie** [comment]
Glad you figured it out, though quick heads up. The console has the version number. That is the quickest way to confirm you are looking at the latest.

![Screen Shot 2021-06-12 at 8 33 46 AM](https://user-images.githubusercontent.com/5713670/121781308-f3a26980-cb58-11eb-966c-56dd28bfa4bd.png)

**Comment by chadstewart** [comment]
Ahh okay, completely forgot about that. I think I just forgot to update the project honestly. I'll definitely keep this in mind moving forward. Thanks much!

**Comment by chadstewart** [comment]
So I updated Storybook with all the UI elements I came across in the project. I wanted to ask how do I get someone to review my work? Should I just create a pull request and let people review it there or should I link someone to my repo and have them pull the branch from my forked repo?

This is the branch in my repo in question by the way: https://github.com/chadstewart/open-sauced/tree/updating-storybook

**Comment by 0-vortex** [comment]
> So I updated Storybook with all the UI elements I came across in the project. I wanted to ask how do I get someone to review my work? Should I just create a pull request and let people review it there or should I link someone to my repo and have them pull the branch from my forked repo?
> 
> This is the branch in my repo in question by the way: [https://github.com/chadstewart/open-sauced/tree/updating-storybook](https://github.com/chadstewart/open-sauced/tree/updating-storybook?rgh-link-date=2021-06-14T17%3A57%3A20Z)

Check out the contribution docs over at: https://github.com/open-sauced/open-sauced#-contributing - to answer your question directly, yes, you should open a PR, if you are not sure you can keep it as a draft and ask for additional assistance (there is a checkbox in the PR template specifically for your use case) - say you need someone else to give it a spin and as soon as someone is able to, they will :D

If however your PR is not checked in a timely manner do ping the @open-sauced/triage team or the gan himself @bdougie !

**Comment by chadstewart** [comment]
Ahh okay, no problem. Thanks for the quick reply! Will do so in a bit.

**Comment by mtfoley** [comment]
@bdougie i saw that PR #1037 got merged.  Are there outstanding pieces to close this one?

**Comment by 0-vortex** [comment]
> @bdougie i saw that PR #1037 got merged. Are there outstanding pieces to close this one?

We can open any minor chores on new specific storybook issues defined by their respective components. Not dragging this on so me can focus on new features/design, judging by @chadstewart quality of work I doubt there's anything we missed :D
